// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdLiEDDw5pY-2xByZwAGkCx6fFhxtBZ4',
    appId: '1:42666403791:web:1a10478c31459480a014ba',
    messagingSenderId: '42666403791',
    projectId: 'nlrc-rfid',
    authDomain: 'nlrc-rfid.firebaseapp.com',
    storageBucket: 'nlrc-rfid.firebasestorage.app',
    measurementId: 'G-FFRCZPP2ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPsXpPoKm07TUa1X_rp0ppww0p6Fjkcs',
    appId: '1:42666403791:android:52f8b0e2c4c1b2bda014ba',
    messagingSenderId: '42666403791',
    projectId: 'nlrc-rfid',
    storageBucket: 'nlrc-rfid.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDdLiEDDw5pY-2xByZwAGkCx6fFhxtBZ4',
    appId: '1:42666403791:web:95564734d45fdaa1a014ba',
    messagingSenderId: '42666403791',
    projectId: 'nlrc-rfid',
    authDomain: 'nlrc-rfid.firebaseapp.com',
    storageBucket: 'nlrc-rfid.firebasestorage.app',
    measurementId: 'G-QH3E3LE4FR',
  );
}
